name: 'OtterWise Coverage Upload'
description: 'Upload code coverage to OtterWise'

branding:
  color: 'black'
  icon: 'check'

inputs:
  token:
    description: 'OtterWise Repo token'
    required: true
  file:
    description: 'Path to coverage file'
    required: false
    default: ''
  bash-uploader-sha:
    description: 'Path to coverage file'
    required: false
    default: 'main'
  type-coverage-file:
    description: 'Path to type coverage file'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Upload coverage
      shell: bash
      run: |
        CMD="bash <(curl -s https://raw.githubusercontent.com/getOtterWise/bash-uploader/${{ inputs.bash-uploader-sha }}/uploader.sh) --repo-token ${{ inputs.token }}"
        
        if [ -n "${{ inputs.file }}" ]; then
          CMD="$CMD --file ${{ inputs.file }}"
        fi
        
        if [ -n "${{ inputs.type-coverage-file }}" ]; then
          CMD="$CMD --type-coverage-file ${{ inputs.type-coverage-file }}"
        fi
        
        eval $CMD
